# render.yaml
services:
  - type: web
    name: taxeasy-za-2025
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CSRF_SECRET
        generateValue: true
